# Dependabot configuration for AsBuiltReport.Core
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Monitor GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    open-pull-requests-limit: 5

  # Monitor PowerShell modules (via manifest)
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "powershell"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 5
    ignore:
      # PScribo updates should be reviewed manually
      - dependency-name: "PScribo"
        update-types: ["version-update:semver-major"]
